import "./globals.css";
import { Inter } from "next/font/google";
import { Titillium_Web } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const titllium = Titillium_Web({
  weight: ["200", "300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-zinc-900 ${titllium.className}`}>{children}</body>
    </html>
  );
}
